#include "Ball.h"
#include <iostream>
#include <random>

Ball::Ball(float x_pos, float y_pos, float x_vel, float y_vel) : Player(x_pos,y_pos,"Ball") {
	getRect().h = 30;
	getRect().w = 30;
	getRect().x = x_pos;
	getRect().y = y_pos;


}

/*
	@param: <int>randomNumber

	This function utilizes the random number generated by generateNumber()
	In order to randomly move the ball towards player1 or player2 at the beginning of the round 

*/
void Ball::startBall(int randomNumber) {
	


	if (randomNumber == 0) { this->setX(this->getRect().x + 0.01); }
	else { this->setX(this->getRect().x - 0.01); }



}


/*
	Simple function that generates a random number in the range of [0,1]

	This Function will be used to at the beginning of the round to determine
	if the ball will go towards player1 or player2
*/
int Ball::generateNumber() {
	std::random_device seed;
	std::mt19937 gen(seed());
	std::uniform_int_distribution<> dist(0, 1);

	int left_or_right = dist(gen);

	return left_or_right;
}


void Ball::checkCollision(Player player1, Player player2) {
	







}